service: spark-joy

provider:
    name: aws
    runtime: nodejs8.10
    
    
functions:
    graphql:
        handler: dist/graphql.handler
        events:
            - http:
                  path: hello
                  method: GET
                  cors: true
            
